import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(-2*np.pi, 2*np.pi, 100)
y_sin = np.sin(x)
y_cos = np.cos(x)
plt.plot(x, y_sin, label='sin(x)')
plt.plot(x, y_cos, label='cos(x)')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Plot of sin(x) and cos(x)')
plt.legend()
plt.show()

x = np.linspace(-2*np.pi, 2*np.pi, 100)
y_sin = np.sin(x)
y_cos = np.cos(x)
plt.figure(1)
plt.plot(x, y_sin)
plt.xlabel('x')
plt.ylabel('y')
plt.title('Plot of sin(x)')
plt.figure(2)
plt.plot(x, y_cos)
plt.xlabel('x')
plt.ylabel('y')
plt.title('Plot of cos(x)')
plt.show()

x = np.linspace(-2*np.pi, 2*np.pi, 100)
y_sin = np.sin(x)
y_cos = np.cos(x)
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(6, 8))
ax1.plot(x, y_sin, label='sin(x)')
ax1.set_xlabel('x')
ax1.set_ylabel('y')
ax1.set_title('Plot of sin(x)')
ax1.legend()
ax2.plot(x, y_cos, label='cos(x)')
ax2.set_xlabel('x')
ax2.set_ylabel('y')
ax2.set_title('Plot of cos(x)')
ax2.legend()
plt.tight_layout()
plt.show()